### ISSUE TITLE
[FEATURE] Setting up React application

### ISSUE THREAD

**Issue by c12i** [BuildForSDGCohort2/Team-180-a-Frontend#4]
**What Functionality would you like to add or fix?**
## Setting up React application

**Describe this Functionality/fix**
Will be adding the following functionalities:
- Set up basic routing with [React-Router](https://reactrouter.com/)
- Set up [Redux](https://react-redux.js.org/):
   - Redux middleware ([thunks](https://github.com/reduxjs/redux-thunk) and [logger](https://www.npmjs.com/package/redux-logger) for development)
   - Redux Store and Global State
   - Reducers and Root Reducer
   - Selectors (see [reselect](https://github.com/reduxjs/reselect))
- Set up eslint
- Create global [axios](https://github.com/axios/axios) instance for making http requests within the client
- Set up [enzyme](https://enzymejs.github.io/enzyme/) for snapshot testing

**Comment by c12i** [comment]
@Esther-Wavinya  I am assuming the team is fine with using Redux for state management, we are always free to pick and choose unanimously what we would like to use

**Comment by Esther-Wavinya** [comment]
Yes we are okay using redux

**Comment by Esther-Wavinya** [comment]
@collinsmuriuki Are you going to set it up?

**Comment by c12i** [comment]
Yes, will do
